



var datesss = [
    "Müze gezi",
    "Doğa yürüyüşü",
    "Yıldızlı piknik",
    "Yeni spor deneyimi",
    "Dans dersi",
    "Sinema gecesi",
    "Hafta sonu kaçamağı",
    "El sanatları etkinliği",
    "Konser izleme",
    "Şehir turu",
    "Yıldız izleme",
    "Müzik enstrümanı",
    "Piknik",
    "Meyve bahçesi",
    "Hayvan barınağı",
    "Macera parkı",
    "Mini golf",
    "Evcil hayvan barınağı",
    "Çömlek atölyesi",
    "Müzik festivali",
    "Sanat galerisi",
    "Restoran deneyimi",
    "Dans parti",
    "Yüzme",
    "Bisiklet turu",
    "Buz pateni",
    "Kamp ateşi",
    "Plaj günü",
    "Film maratonu",
    "Karaoke",
    "Akşam pikniği",
    "Kısa tatil",
    "Resim dersi",
    "Deniz ürünleri yemeği",
    "Akşam yemeği",
    "Kamp ateşi",
    "Sanat sergisi",
    "Eskrim dersi",
    "Bisiklet turu",
    "Şarap tadımı",
    "Bilardo oynama",
    "Müze gezi",
    "Sirk gösterisi",
    "Balık tutma",
    "Yaratıcı resim",
    "Dondurma tatma",
    "Balon turu",
    "Doğa fotoğrafçılığı",
    "Çiftlik gezisi",
    "Fotoğraf yürüyüşü",
    "Yelkenli tekne turu",
    "Yerel tiyatro",
    "Evcil hayvan kafe",

    "Yemek pişirme gecesi",
    "Müze gezi",
    "Doğa yürüyüşü",
    "Yıldızlı piknik",
    "Yeni spor deneyimi",
    "Kitap kulübü",
    "Dans dersi",
    "Çiftlik ziyareti",
    "Atlıkarınca parkı",
    "Sinema gecesi",
    "Hafta sonu kaçamağı",
    "El sanatları etkinliği",
    "Konser izleme",
    "Şehir turu",
    "Yıldız izleme",
    "Müzik enstrümanı",
    "Piknik",
    "Yerel etkinlik",
    "Meyve bahçesi",
    "Hayvan barınağı",
    "Macera parkı",
    "Mini golf",
    "Müzik enstrümanı",
    "Evcil hayvan barınağı",
    "Çömlek atölyesi",
    "Müzik festivali",
    "Sanat galerisi",
    "Restoran deneyimi",
    "Dans parti",
    "Yüzme",
    "Bisiklet turu",
    "Buz pateni",
    "Kamp ateşi",
    "Plaj günü",
    "Sanat etkinliği",
    "Film maratonu",
    "Karaoke",
    "Mangal partisi",
    "Gece yürüyüşü",
    "Kısa tatil",
    "Karaoke",
    "Resim dersi",
    "Deniz ürünleri yemeği",
    "Fotoğraf gezisi",
    "Akşam pikniği",
    "Karaoke",
    "Kokteyl yapma",
    "Güneş batışı izleme",
    "Bisiklet gezisi",
    "Kuş gözlemi",
    "Köy gezisi",
    "Karaoke",
    "Elma toplama",
    "Yüzme",
    "Gece sineması",
    "Ev partisi",
    "Dans gecesi",
    "Karaoke",
    "Yıldızlı gece",
    "Bahçe partisi",
    "Pasta yapma",
    "Gece yemeği",
    "Kamp ateşi",
    "Sanat sergisi",
    "Hayvanat bahçesi",
    "Eskrim dersi",
    "Bisiklet turu",
    "Şarap tadımı",
    "Bilardo oynama",
    "Müze gezi",
    "Karaoke",
    "Sirk gösterisi",
    "Balık tutma",
    "Yaratıcı resim",
    "Karaoke",
    "Dondurma tatma",
    "Balon turu",
    "Doğa fotoğrafçılığı",
    "Mangal partisi",
    "Çiftlik gezisi",
    "Dart oynama",
    "Fotoğraf yürüyüşü",
    "Gökyüzü izleme",
    "Yelkenli tekne turu",
    "Yerel tiyatro",
    "Evcil hayvan kafe",
    "Karaoke",
    "Gün batımı yürüyüşü",
    "Dans etme dersi",
    "Müzikal gösteri",
    "Süs bitkisi dikme",
    "Karaoke"
]



var seriesss = [
    "Breaking Bad",
    "Game of Thrones",
    "The Sopranos",
    "The Wire",
    "Friends",
    "Stranger Things",
    "The Crown",
    "Sherlock",
    "Black Mirror",
    "Narcos",
    "Westworld",
    "Fargo",
    "Mindhunter",
    "The Mandalorian",
    "The Office (US)",
    "Peaky Blinders",
    "Better Call Saul",
    "Chernobyl",
    "The Witcher",
    "Rick and Morty",
    "The Marvelous Mrs. Maisel",
    "True Detective",
    "The Handmaid's Tale",
    "Money Heist",
    "The Boys",
    "The Umbrella Academy",
    "Dark",
    "Stranger Things",
    "Sherlock",
    "Black Mirror",
    "The Crown",
    "Narcos",
    "Fargo",
    "Mindhunter",
    "The Mandalorian",
    "The Office (US)",
    "Peaky Blinders",
    "Better Call Saul",
    "Chernobyl",
    "The Witcher",
    "Rick and Morty",
    "The Marvelous Mrs. Maisel",
    "True Detective",
    "The Handmaid's Tale",
    "Money Heist",
    "The Boys",
    "The Umbrella Academy",
    "Dark",
    "The Haunting of Hill House",
    "Breaking Bad",
    "Game of Thrones",
    "The Sopranos",
    "The Wire",
    "Friends",
    "Brooklyn Nine-Nine",
    "How I Met Your Mother",
    "Arrested Development",
    "The Big Bang Theory",
    "The Simpsons",
    "Futurama",
    "Parks and Recreation",
    "The Office (UK)",
    "It's Always Sunny in Philadelphia",
    "The Good Place",
    "Scrubs",
    "Community",
    "Modern Family",
    "The IT Crowd",
    "The Marvelous Mrs. Maisel",
    "Curb Your Enthusiasm",
    "Fleabag",
    "Veep",
    "Barry",
    "Ted Lasso",
    "Atlanta",
    "Brooklyn Nine-Nine",
    "How I Met Your Mother",
    "Arrested Development",
    "The Big Bang Theory",
    "The Simpsons",
    "Futurama",
    "Parks and Recreation",
    "The Office (UK)",
    "It's Always Sunny in Philadelphia",
    "The Good Place",
    "Scrubs",
    "Community",
    "Modern Family",
    "The IT Crowd",
    "Curb Your Enthusiasm",
    "Fleabag",
    "Veep",
    "Barry",
    "Ted Lasso",
    "Atlanta",
    "The Marvelous Mrs. Maisel",
    "Curb Your Enthusiasm",
    "Fleabag",
    "Veep",
    "Barry",
    "Ted Lasso",
    "Atlanta",
    "The Haunting of Hill House"
]


var moviesss = [
    "The Shawshank Redemption",
    "The Godfather",
    "The Dark Knight",
    "12 Angry Men",
    "Schindler's List",
    "Pulp Fiction",
    "Fight Club",
    "Forrest Gump",
    "Inception",
    "The Matrix",
    "Goodfellas",
    "One Flew Over the Cuckoo's Nest",
    "Seven Samurai",
    "The Silence of the Lambs",
    "City of God",
    "Life is Beautiful",
    "Saving Private Ryan",
    "Spirited Away",
    "Interstellar",
    "The Departed",
    "Gladiator",
    "The Prestige",
    "The Lion King",
    "Back to the Future",
    "The Shining",
    "American History X",
    "Django Unchained",
    "Apocalypse Now",
    "Raiders of the Lost Ark",
    "Alien",
    "Memento",
    "Amélie",
    "Taxi Driver",
    "Terminator 2: Judgment Day",
    "Blade Runner",
    "Eternal Sunshine of the Spotless Mind",
    "Lawrence of Arabia",
    "A Beautiful Mind",
    "The Bridge on the River Kwai",
    "2001: A Space Odyssey",
    "The Godfather: Part II",
    "The Good, the Bad and the Ugly",
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Lord of the Rings: The Two Towers",
    "The Lord of the Rings: The Return of the King",
    "Schindler's List",
    "The Pianist",
    "The Green Mile",
    "The Intouchables",
    "Whiplash",
    "The Usual Suspects",
    "The Terminator",
    "The Truman Show",
    "The Grand Budapest Hotel",
    "The Big Lebowski",
    "Gran Torino",
    "A Clockwork Orange",
    "Braveheart",
    "Full Metal Jacket",
    "To Kill a Mockingbird",
    "Raging Bull",
    "Pan's Labyrinth",
    "The Gold Rush",
    "La La Land",
    "Casablanca",
    "The Wizard of Oz",
    "Psycho",
    "The Third Man",
    "Chinatown",
    "Some Like It Hot",
    "Gone with the Wind",
    "Rear Window",
    "The Great Escape",
    "The Deer Hunter",
    "Rocky",
    "Jurassic Park",
    "The Exorcist",
    "Jaws",
    "Close Encounters of the Third Kind",
    "Ferris Bueller's Day Off",
    "Die Hard",
    "The Breakfast Club",
    "The Truman Show",
    "The King's Speech",
    "The Artist",
    "Argo",
    "Birdman",
    "Spotlight",
    "Moonlight",
    "Green Book",
    "Parasite",
    "The Grand Budapest Hotel",
    "The Shawshank Redemption",
    "The Godfather",
    "The Dark Knight",
    "12 Angry Men",
    "Schindler's List",
    "Pulp Fiction",
    "Fight Club",
    "Forrest Gump",
    "Inception",
    "The Matrix"
]
